# Workflow for running check-in tests locally (e.g., via https://github.com/nektos/act)
#
# Note:
# - Invoked via tools/local-workflows.sh:
#   act --container-architecture linux/amd64 --pull="false" -P "ubuntu-latest=local/test-act" -W ./.github/workflows/act.yml
#

name: Act-Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ## TODO: [3.8 ... 3.10]
        python-version: ["3.9"]

    container:
      image: local/test-act
      options: --user=root

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Environment
        run: |
          echo "PATH=$PATH" >> $GITHUB_ENV
          echo "PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.9/dist-packages" >> $GITHUB_ENV

      - name: Run Python Tests
        run: |
          PYTHONPATH="$(pwd):$PYTHONPATH" ./tools/run_tests.bash

      ## TODO:
      ## See https://github.com/tomasohara/shell-scripts/blob/main/tests/batspp_report.py
      ## - name: Run Bats-PP Alias Tests
      ##   run: |
      ##     PYTHONPATH="$(pwd):$PYTHONPATH" bash tests/summary_stats.bash
