# This workflow will install Python dependencies, run tests and lint, using
# different versions of Python.
#
# Notes:
# - Requires special permission for Github workflows.
# - For more information see following:
#     https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
#     https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# - Based initially on version from https://github.com/LimaBD/batspp.
#

name: tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ## TODO: python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.8", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # Specific requirement for SoundFile
        sudo apt-get install libsndfile1

        # Mezcla requirements
        # Note: this installs optional packages not used for most scripts
        # TODO: make less hackish here and in the requirements file (the basis for the hack)
        pip install --verbose $(perl -00 -pe 's/^#opt#\s*//gm;' ./requirements.txt | grep -v '^#')
    - name: Test with pytest
      run: |
        ## BAD: PYTHONPATH="$(dirname $(realpath -s $0))/mezcla/:$PYTHONPATH" coverage run -m pytest ./mezcla/tests/
        ## DEBUG:
        echo "\$0=$0"
        PYTHONPATH="$(realpath --no-symlinks $(dirname $0))/mezcla/:$PYTHONPATH" coverage run -m pytest ./mezcla/tests/
        coverage xml
